local mod = get_mod("toughness_tracker")

return {
	name = mod:localize("mod_title"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = {
			{["setting_id"] = "total_toughness",
				["type"] = "checkbox",
				["default_value"] = true,
			},
			{["setting_id"] = "melee_toughness",
				["type"] = "checkbox",
				["default_value"] = true,
			},
			{["setting_id"] = "exhilarating_takedown",
				["type"] = "checkbox",
				["default_value"] = false,
			},
			{["setting_id"] = "confirmed_kill",
				["type"] = "checkbox",
				["default_value"] = false,
			},
			{["setting_id"] = "out_for_blood",
				["type"] = "checkbox",
				["default_value"] = false,
			},
			{["setting_id"] = "born_leader",
				["type"] = "checkbox",
				["default_value"] = false,
			},
			{["setting_id"] = "debug",
				["type"] = "checkbox",
				["default_value"] = false,
			},
		},
	},
}
